{
  "uid" : "c1e8f49342557df0",
  "name" : "test",
  "fullName" : "testPackage01.SHAFTWizard.Test_Wizard_DB.test",
  "historyId" : "61ae3289c295ee84141d88d3d0a1084c",
  "time" : {
    "start" : 1649056935160,
    "stop" : 1649056935173,
    "duration" : 13
  },
  "status" : "failed",
  "statusMessage" : "Database Action \"<init>\" failed. With the following test data \"Custom Connection String: \"\"\".",
  "statusTrace" : "java.lang.AssertionError: Database Action \"<init>\" failed. With the following test data \"Custom Connection String: \"\"\".\n\tat org.testng.Assert.fail(Assert.java:110)\n\tat com.shaft.db.DatabaseActions.failAction(DatabaseActions.java:204)\n\tat com.shaft.db.DatabaseActions.failAction(DatabaseActions.java:210)\n\tat com.shaft.db.DatabaseActions.<init>(DatabaseActions.java:61)\n\tat com.shaft.driver.SHAFT$DB.performDatabaseActions(SHAFT.java:169)\n\tat testPackage01.SHAFTWizard.Test_Wizard_DB.test(Test_Wizard_DB.java:12)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:808)\n\tat org.testng.TestRunner.run(TestRunner.java:603)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:429)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:326)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1169)\n\tat org.testng.TestNG.runSuites(TestNG.java:1092)\n\tat org.testng.TestNG.run(TestNG.java:1060)\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)\n\tat org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)\n\tat org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)\n\tat org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "setupActivities",
    "time" : {
      "start" : 1649056899698,
      "stop" : 1649056900518,
      "duration" : 820
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ {
      "name" : "Folder \"extent-reports\" was not found, it may have already been deleted.",
      "time" : {
        "start" : 1649056899856,
        "stop" : 1649056899857,
        "duration" : 1
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "logText",
        "value" : "Folder \"extent-reports\" was not found, it may have already been deleted."
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    }, {
      "name" : "Terminal Action \"PerformTerminalCommands\" successfully performed. With the following test data \"Host Name: \"localHost\" | Command: \"chmod u+x generateJdk.sh\" | Exit Status: \"1\"\".",
      "time" : {
        "start" : 1649056900515,
        "stop" : 1649056900517,
        "duration" : 2
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "8056e34f68f45169",
        "name" : "Terminal Action Actual Result - Command Log",
        "source" : "8056e34f68f45169.txt",
        "type" : "text/plain",
        "size" : 64
      } ],
      "parameters" : [ {
        "name" : "logText",
        "value" : "Terminal Action \"PerformTerminalCommands\" successfully performed. With the following test data \"Host Name: \"localHost\" | Command: \"chmod u+x generateJdk.sh\" | Exit Status: \"1\"\"."
      }, {
        "name" : "attachments",
        "value" : "[[Terminal Action Actual Result, Command Log, chmod: cannot access 'generateJdk.sh': No such file or directory]]"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 1,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "624cad70d624c55a",
      "name" : "SHAFT Links - Important",
      "source" : "624cad70d624c55a.uri",
      "type" : "text/uri-list",
      "size" : 346
    } ],
    "parameters" : [ ],
    "stepsCount" : 2,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "Database Action \"<init>\" failed. With the following test data \"Custom Connection String: \"\"\".",
    "statusTrace" : "java.lang.AssertionError: Database Action \"<init>\" failed. With the following test data \"Custom Connection String: \"\"\".\n\tat org.testng.Assert.fail(Assert.java:110)\n\tat com.shaft.db.DatabaseActions.failAction(DatabaseActions.java:204)\n\tat com.shaft.db.DatabaseActions.failAction(DatabaseActions.java:210)\n\tat com.shaft.db.DatabaseActions.<init>(DatabaseActions.java:61)\n\tat com.shaft.driver.SHAFT$DB.performDatabaseActions(SHAFT.java:169)\n\tat testPackage01.SHAFTWizard.Test_Wizard_DB.test(Test_Wizard_DB.java:12)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:808)\n\tat org.testng.TestRunner.run(TestRunner.java:603)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:429)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:326)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1169)\n\tat org.testng.TestNG.runSuites(TestNG.java:1092)\n\tat org.testng.TestNG.run(TestNG.java:1060)\n\tat org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)\n\tat org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)\n\tat org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)\n\tat org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)\n\tat org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)\n\tat org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)\n\tat org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)\n\tat org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)\n",
    "steps" : [ {
      "name" : "Database Action \"<init>\" failed. With the following test data \"Custom Connection String: \"\"\".",
      "time" : {
        "start" : 1649056935163,
        "stop" : 1649056935163,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "logText",
        "value" : "Database Action \"<init>\" failed. With the following test data \"Custom Connection String: \"\"\"."
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "6831806fe377679e",
      "name" : "SHAFT Engine Logs - Current Method log: test",
      "source" : "6831806fe377679e.txt",
      "type" : "text/plain",
      "size" : 558
    } ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "teardownActivities",
    "time" : {
      "start" : 1649058393508,
      "stop" : 1649058394314,
      "duration" : 806
    },
    "description" : "",
    "status" : "passed",
    "steps" : [ {
      "name" : "Successfully Closed All Drivers.",
      "time" : {
        "start" : 1649058393635,
        "stop" : 1649058393635,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ {
        "name" : "logText",
        "value" : "Successfully Closed All Drivers."
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    }, {
      "name" : "Issue Summary: Total Issues = 7, New issues for Failed Tests = 5, Open issues for Passed Tests = 2, Open issues for Failed Tests = 0. Kindly check the attached Issue details.",
      "time" : {
        "start" : 1649058393644,
        "stop" : 1649058393644,
        "duration" : 0
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "76dde7958d3753c6",
        "name" : "SHAFT Engine Logs - Issues log CSV: 20220404-074633",
        "source" : "76dde7958d3753c6.csv",
        "type" : "text/csv",
        "size" : 833
      } ],
      "parameters" : [ {
        "name" : "logText",
        "value" : "Issue Summary: Total Issues = 7, New issues for Failed Tests = 5, Open issues for Passed Tests = 2, Open issues for Failed Tests = 0. Kindly check the attached Issue details."
      }, {
        "name" : "attachments",
        "value" : "[[SHAFT Engine Logs, Issues log CSV: 20220404-074633, java.io.ByteArrayInputStream@6a50ead]]"
      } ],
      "stepsCount" : 0,
      "attachmentsCount" : 1,
      "shouldDisplayMessage" : false,
      "hasContent" : true
    } ],
    "attachments" : [ {
      "uid" : "892f13e702ea1217",
      "name" : "Selenium WebDriver Logs - browser",
      "source" : "892f13e702ea1217.txt",
      "type" : "text/plain",
      "size" : 294
    }, {
      "uid" : "4919222febc86fc3",
      "name" : "SHAFT Engine Logs - Execution log: 20220404-074633",
      "source" : "4919222febc86fc3.txt",
      "type" : "text/plain",
      "size" : 292502
    }, {
      "uid" : "86ea82a2bae8e670",
      "name" : "HTML - Extent Emailable Execution Report",
      "source" : "86ea82a2bae8e670.html",
      "type" : "text/html",
      "size" : 10712589
    } ],
    "parameters" : [ ],
    "stepsCount" : 2,
    "attachmentsCount" : 4,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "package",
    "value" : "testPackage01.SHAFTWizard.Test_Wizard_DB"
  }, {
    "name" : "testClass",
    "value" : "testPackage01.SHAFTWizard.Test_Wizard_DB"
  }, {
    "name" : "testMethod",
    "value" : "test"
  }, {
    "name" : "parentSuite",
    "value" : "Suite"
  }, {
    "name" : "suite",
    "value" : "Test"
  }, {
    "name" : "subSuite",
    "value" : "testPackage01.SHAFTWizard.Test_Wizard_DB"
  }, {
    "name" : "host",
    "value" : "fv-az290-429"
  }, {
    "name" : "thread",
    "value" : "3454@fv-az290-429.main(1)"
  }, {
    "name" : "framework",
    "value" : "testng"
  }, {
    "name" : "language",
    "value" : "java"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "c1e8f49342557df0.json",
  "parameterValues" : [ ]
}